[package]
name = "nft-marketplace"
version = "1.0.0"
authors = ["Lokesh Kumar <https//github.com/codeTIT4N>"]
license = "MIT"

[addresses]
publisher = "0xe6d4c56594382cd61f530de46d353a32db17226b4ee9a1ae9ba19df9485bcbcb"
aptos_framework = "_"
aptos_std = "_"
aptos_token = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
