[package]
name = "nft-marketplace"
version = "1.0.0"
authors = ["Lokesh Kumar <https//github.com/codeTIT4N>"]
license = "MIT"

[addresses]
publisher = "0xd044cad4fbf9ed6870db3ce00cccc7b93f0679a8a9b199b3f2834a61686dba56"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
aptos_token = "0x3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "mainnet" }

[dev-dependencies]
