[package]
name = "collection"
version = "1.0.0"
authors = []

[addresses]
publisher = "573bd311d009e2be5f83f73afceebe4553d8d32ebcd0344e1206bfd7907c133d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
