[package]
name = "aptos-counter"
version = "1.0.0"
authors = []

[addresses]
publisher = "11c630936432aac808dea3e709c4e98a77ad6e39744396691807101aa212d80d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
