[package]
name = "aptos-counter"
version = "1.0.0"
authors = []

[addresses]
publisher = "17fca4b7f0d4635e539f94cbec8f84214456305766b00fdf865660bdf5c2fa1b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
